add method to reset the histogram
mcollina/native-hdr-histogram pull request #10
Opened 2016-11-03 01:18 UTC by thekemkid

This is so I can work on something for https://github.com/mcollina/autocannon/issues/92

2016-11-03 01:20 UTC, thekemkid commented on test.js
> +  t.equal(instance.min(), 9223372036854776000, 'min is setup')
@mcollina I discovered this tidbit when writing my tests, I have recreated it several times. should this be acceptable? its an empty instance.

2016-11-03 01:21 UTC, thekemkid commented on package.json
> +    "test": "node-pre-gyp install --build-from-source && standard && tap test.js"
Changed this command to ensure when running tests it always rebuilds. Previously it used any existing build, which wasn't optimal in dev.

2016-11-03 01:21 UTC, thekemkid commented on hdr_histogram_wrap.cc
> +  info.GetReturnValue().Set(true);
@mcollina Wasn't sure if I should or should not return here.

2016-11-03 06:42 UTC, mcollina requested changes

2016-11-03 06:42 UTC, mcollina commented on test.js
> +  t.equal(instance.min(), 9223372036854776000, 'min is setup')
Not really.
However it is a bug in the C library. We might open a separate bug there.

2016-11-03 06:42 UTC, mcollina commented on hdr_histogram_wrap.cc
> +  info.GetReturnValue().Set(true);
IMHO we should return the histogram, or undefined.

2016-11-03 09:46 UTC, thekemkid commented on test.js
> +  t.equal(instance.min(), 9223372036854776000, 'min is setup')
👍

2016-11-03 09:47 UTC, GlenTiki commented on hdr_histogram_wrap.cc
> +  info.GetReturnValue().Set(true);
I'll return the histogram.

2016-11-03 11:56 UTC, mcollina approved these changes
LGTM

2016-11-06 20:37 UTC, thekemkid commented on test.js
> +  t.equal(instance.min(), 9223372036854776000, 'min is setup')
I've done some research on this, I don't believe it the issue we thought it. The min value should be initialised to positive infinity, and max value to negative infinity. It means the check for greater than or less than values are not complex logic trees, and you just use the single variables from initialisation in implementation.

2016-11-06 20:39 UTC, thekemkid commented on test.js
> +  t.equal(instance.min(), 9223372036854776000, 'min is setup')
& relevant issue: https://github.com/HdrHistogram/HdrHistogram/issues/54

2016-11-06 20:40 UTC, merged